{% set name = 'stsci.numdisplay' %}
{% set version = '1.6.2' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '0' %}

about:
    home: https://github.com/GeminiDRSoftware/{{ name }}
    license: BSD
    summary: |
        Package for displaying numpy arrays in DS9 (Gemini fork)

build:
    number: {{ number }}
    preserve_egg_dir: 'yes'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - numpy {{ numpy }}
    - stsci.distutils
    - stsci.tools
    - setuptools
    - python {{ python }}
    run:
    - numpy
    - stsci.tools
    - python

source:
    git_url: https://github.com/GeminiDRSoftware/{{ name }}.git
    git_tag: 1.6.2

test:
    imports:
    - stsci.numdisplay
